-- Seed public workflow templates exported from production.
-- Generated by scripts/export-workflow-seed.mjs.
-- Manual only: run scripts/apply-workflow-seed.mjs when you intentionally want to import/update templates.
-- Secrets and expiring VPS static asset URLs are stripped; input nodes use session uploads.

INSERT INTO users (email, full_name, role, is_active)
VALUES ('seed-workflows@local.dev', 'Seed Workflow Templates', 'staff', true)
ON CONFLICT (email) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  is_active = true;

WITH seed_user AS (
  SELECT id FROM users WHERE email = 'seed-workflows@local.dev'
),
seed_workflows(slug, name, description, definition, is_active) AS (
  VALUES
  (
    'linux-create-image',
    ' Create Image',
    'Sinh ảnh từ prompt tự do bằng Qwen-Image-Edit-2509 (hoặc Gemini). Mặc định text→image (không cần ảnh mẫu) — chỉ cần sửa prompt trong node Create Image rồi Test. Muốn chỉnh-ảnh: thêm node Input Image (Source=URL hoặc Upload) nối vào cổng "Ảnh 1".

Template seed cho worker Linux/CUDA.',
    '{"edges":[{"id":"e1","data":{},"source":"create-image-main","target":"output-main"}],"nodes":[{"id":"create-image-main","data":{"config":{"apiKey":"","prompt":"A clean cinematic product concept image, premium studio lighting, high detail, photorealistic","quality":"standard","provider":"qwen","inputCount":0,"aspectRatio":"auto"}},"type":"create-image","position":{"x":-112,"y":-368}},{"id":"output-main","data":{"config":{"field":"image","format":"image"}},"type":"output","position":{"x":272,"y":-368}}]}'::jsonb,
    true
  ),
  (
    'linux-thay-do-mau',
    ' Transfer Image',
    'Mặc sản phẩm lên người mẫu: Ảnh mẫu + Ảnh sản phẩm -> Try-On (Qwen-Image-Edit) -> giải phóng GPU -> ảnh kết quả.

Template seed cho worker Linux/CUDA.',
    '{"edges":[{"id":"e1","data":{},"source":"input-model","target":"tryon-main","targetHandle":"model"},{"id":"e2","data":{},"source":"input-product","target":"tryon-main","targetHandle":"product"},{"id":"e3","data":{},"source":"tryon-main","target":"gpu-free"},{"id":"e4","data":{},"source":"gpu-free","target":"output-main"}],"nodes":[{"id":"input-model","data":{"config":{"url":"","field":"modelImage","label":"Ảnh người mẫu","source":"session","purpose":"generic","libraryId":"","staticUrl":"","staticData":"","staticMime":"","staticName":"","staticPath":"","staticSize":0,"staticText":"","contentType":"image","staticBucket":""}},"type":"input","position":{"x":16,"y":-80}},{"id":"input-product","data":{"config":{"url":"","field":"productImage","label":"Ảnh sản phẩm","source":"session","purpose":"generic","libraryId":"","staticUrl":"","staticData":"","staticMime":"","staticName":"","staticPath":"","staticSize":0,"staticText":"","contentType":"image","staticBucket":""}},"type":"input","position":{"x":16,"y":400}},{"id":"tryon-main","data":{"config":{"label":"Thử đồ (Qwen-Image-Edit)","apiKey":"","provider":"qwen","autoAnalyze":true,"garmentType":"auto"}},"type":"tryon","position":{"x":512,"y":160}},{"id":"gpu-free","data":{"config":{"label":"Giải phóng GPU","force_stop":true,"max_wait_sec":45}},"type":"gpu-free","position":{"x":816,"y":224}},{"id":"output-main","data":{"config":{"format":"image"}},"type":"output","position":{"x":1136,"y":48}}]}'::jsonb,
    true
  )
)
INSERT INTO workflows (user_id, slug, name, description, definition, is_public, is_active)
SELECT seed_user.id, seed_workflows.slug, seed_workflows.name, seed_workflows.description,
       seed_workflows.definition, true, seed_workflows.is_active
FROM seed_user, seed_workflows
ON CONFLICT (user_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  definition = EXCLUDED.definition,
  is_public = true,
  is_active = EXCLUDED.is_active,
  updated_at = now();
