"""Assemble one job's files into the manifest the existing batch runner consumes.

Pure: no Telegram types, no subprocess, no I/O beyond writing the manifest
text itself (`write_manifest`). Required slots are read from
`batchlib.pipelines.PIPELINES`/`STAGES` rather than hardcoded here, so a new
pipeline added there cannot silently ask the user for the wrong files — the
mistake would otherwise only surface as a wasted paid render.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from batchlib.pipelines import PIPELINES, STAGES, required_roles

from .ingest import Probe, describe, suggest_preset


@dataclass
class Job:
    slots: dict[str, Path]
    probes: dict[str, Probe]
    pipeline: str


def _driver_stage(pipeline: str) -> str | None:
    """Which stage of `pipeline` actually consumes the `driver` material.

    STAGES has no notion of "video" vs "image" — that typing lives only in
    ingest.Probe. So which *role* a video maps to (driver) is domain
    knowledge, not something derivable from STAGES; but which *stage*
    consumes that role for a given pipeline IS derivable, and deriving it
    avoids hardcoding "motion" when a pipeline instead runs character-swap.
    """
    for stage_name in PIPELINES.get(pipeline, []):
        stage = STAGES[stage_name]
        for source in stage.inputs.values():
            if "material:driver" in source.split("|"):
                return stage_name
    return None


def slot_for(probe: Probe, job: Job) -> str | None:
    """Infer a slot from structural fact alone, never from a filename guess.

    A video can only ever be the `driver`: across every Stage in
    batchlib/pipelines.py, "material:driver" is the sole material role ever
    fed by a video file (motion's `motion` field, character-swap's `video`
    field). An image, by contrast, is genuinely ambiguous among character,
    outfit and background — guessing there would burn a real $1 batch on a
    mislabeled outfit, so we return None and let the caller ask.
    """
    if probe.kind == "video":
        return "driver"
    return None


def missing_slots(job: Job) -> list[str]:
    """Required slots not yet filled, derived from PIPELINES/STAGES.

    Never a hardcoded list: required_roles()/optional_roles() walk the real
    Stage.inputs declarations, so a pipeline added later without a matching
    hardcoded list here can't silently ask for the wrong files.
    """
    needed = required_roles(job.pipeline)
    return sorted(needed - set(job.slots))


def render_manifest(job: Job, *, now) -> str:
    """Render the YAML the existing batch runner (`batchlib.manifest`) loads.

    The header carries the ffprobe numbers as dated comments — what a user
    writes by hand today per docs/batch-runner.md — so the file still
    explains itself six weeks later. Where the job has a driver, the same
    duration that produced the comment also becomes a real `preset:` param:
    without it the worker falls back to its own frame-count default (81
    frames for `motion`, `drv-5s` for `character-swap` — linux.py:1417,
    :5261), unrelated to the driver's actual measured length, after the
    pod was already rented.
    """
    lines = [
        f"# Generated by the Telegram bot at {now}.",
        f"# Pipeline: {job.pipeline}",
    ]
    for slot in sorted(job.probes):
        probe = job.probes[slot]
        line = f"# {slot}: {describe(probe)}"
        if probe.kind == "video":
            line += f" -> preset {suggest_preset(probe.duration_s)}"
        lines.append(line)

    lines.append("")
    lines.append("runs:")
    lines.append("  - id: job")
    lines.append(f"    pipeline: {job.pipeline}")
    lines.append("    inputs:")
    for slot in sorted(job.slots):
        lines.append(f"      {slot}: {job.slots[slot]}")

    driver_stage = _driver_stage(job.pipeline)
    driver_probe = job.probes.get("driver")
    if driver_stage and driver_probe is not None:
        preset = suggest_preset(driver_probe.duration_s)
        lines.append(f"    {driver_stage}: {{ preset: {preset} }}")

    lines.append("")
    return "\n".join(lines)


def write_manifest(job: Job, path: Path, *, now) -> None:
    """Write the manifest once, before the run. The runner never writes it.

    Byte-identical to what the user approved: this is the only place the
    bot renders text to disk, and it always renders the same job the same
    way given the same `now`, so a re-render before the actual run cannot
    drift from what was shown on the confirmation screen.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_manifest(job, now=now), encoding="utf-8")
