#!/usr/bin/env bash
# scripts/ios-secrets.sh — write ios/Secrets.xcconfig from the root .env.
# Same four keys scripts/vps/api-smoke.sh reads; the app copies them into the
# Keychain on first launch (CredentialVault.seedIfEmpty). Gitignored output.
# Optional: IOS_DEVELOPMENT_TEAM (your personal team id) so a regenerated
# project keeps signing without a click in Xcode.
set -euo pipefail
cd "$(dirname "$0")/.."
get() { grep -E "^$1=" .env | tail -1 | cut -d= -f2- || true; }
out=ios/Secrets.xcconfig
tmp="$out.tmp"
{
  echo "// Generated by scripts/ios-secrets.sh from .env — never commit."
  for k in CONTROL_API_URL CF_ACCESS_CLIENT_ID CF_ACCESS_CLIENT_SECRET CONTROL_API_TOKEN; do
    v="$(get "$k")"
    [ -n "$v" ] || { echo "missing $k in .env" >&2; rm -f "$tmp"; exit 2; }
    # xcconfig: "//" starts a comment; "/$()/" is the documented escape.
    escaped="$(printf '%s' "$v" | sed 's#//#/$()/#')"
    echo "$k = $escaped"
  done
  team="$(get IOS_DEVELOPMENT_TEAM)"
  [ -n "$team" ] && echo "DEVELOPMENT_TEAM = $team"
  true
} > "$tmp"
mv "$tmp" "$out"
echo "wrote $out"
